fortigate:
  url: https://fortigate.example.com
  zone: example.com
  vdom: root
  existingSecret: fortigate-external-dns

ownerID: my-cluster
domainFilters:
  - example.com
sources:
  - service
  - ingress
  - gateway
dryRun: true
